### ISSUE TITLE
Absturz bei Wechsel auf Eigenschaften-Tab im Helden-Tool

### ISSUE THREAD

**Issue by garin1000** [Constructor0987/MeisterGeister#39]
Beim Eingeben eines neuen Helden kommt es bei mir in 100% der Fälle beim Wechsel in den Eigenschaften-Tab zu einer Null-Pointer-Exception.

Version: 2.6.0 / 133   

Source: DSA MeisterGeister
Message: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
Type: System.NullReferenceException

InnerException: -

StackTrace:    bei MeisterGeister.View.General.EnergieControl.SetEnergie()
   bei MeisterGeister.View.General.EnergieControl.OnKämpferChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
   bei System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   bei System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   bei System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   bei System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   bei System.Windows.DependencyObject.InvalidateProperty(DependencyProperty dp, Boolean preserveCurrentValue)
   bei System.Windows.Data.BindingExpressionBase.Invalidate(Boolean isASubPropertyChange)
   bei System.Windows.Data.BindingExpression.TransferValue(Object newValue, Boolean isASubPropertyChange)
   bei System.Windows.Data.BindingExpression.Activate(Object item)
   bei System.Windows.Data.BindingExpression.AttachToContext(AttachAttempt attempt)
   bei System.Windows.Data.BindingExpression.MS.Internal.Data.IDataBindEngineClient.AttachToContext(Boolean lastChance)
   bei MS.Internal.Data.DataBindEngine.Task.Run(Boolean lastChance)
   bei MS.Internal.Data.DataBindEngine.Run(Object arg)
   bei System.Windows.ContextLayoutManager.fireLayoutUpdateEvent()
   bei System.Windows.ContextLayoutManager.UpdateLayout()
   bei System.Windows.Controls.TabItem.OnPreviewGotKeyboardFocus(KeyboardFocusChangedEventArgs e)
   bei System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   bei System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   bei System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   bei System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   bei System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   bei System.Windows.Input.InputManager.ProcessStagingArea()
   bei System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   bei System.Windows.Input.KeyboardDevice.TryChangeFocus(DependencyObject newFocus, IKeyboardInputProvider keyboardInputProvider, Boolean askOld, Boolean askNew, Boolean forceToNullIfFailed)
   bei System.Windows.Input.KeyboardDevice.Focus(DependencyObject focus, Boolean askOld, Boolean askNew, Boolean forceToNullIfFailed)
   bei System.Windows.Input.KeyboardDevice.Focus(IInputElement element)
   bei System.Windows.UIElement.Focus()
   bei System.Windows.Controls.TabItem.SetFocus()
   bei System.Windows.Controls.TabItem.OnMouseLeftButtonDown(MouseButtonEventArgs e)
   bei System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   bei System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   bei System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   bei System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   bei System.Windows.UIElement.OnMouseDownThunk(Object sender, MouseButtonEventArgs e)
   bei System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   bei System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   bei System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   bei System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   bei System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   bei System.Windows.Input.InputManager.ProcessStagingArea()
   bei System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   bei System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   bei System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   bei System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   bei System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   bei MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   bei MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   bei System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   bei System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

Data: 
  System.Object: null
Offene Tools: Helden#Proben#Kampf#Notizen#Kalender#NSCs#Umrechner#Würfel

Systeminformationen

MeisterGeisterID: 613c14dc-186f-45f0-9d2f-1ac96c999e86
Regeledition: DSA 4.1
Betriebssystem: Microsoft Windows NT 6.2.9200.0 (Windows 8)
64bit-System: True
CLR-Version: 4.0.30319.42000
.NET Framework:
  v1.1.4322    SP1
    1033    SP1
  v2.0.50727  2.0.50727.4927  SP2
  v3.0  3.0.30729.4926  SP2
  v3.5  3.5.30729.4926  SP1
  v4  
    Client  4.8.04084
    Full  4.8.04084
  v4.0  
    Client  4.0.0.0
  v4.5
    Full 4.8.04084
SQL-CE-Version: 4.0.8876.1
Arbeitsverzeichnis: E:\DSA MeisterGeister
MeisterGeister-Verzeichnis: E:\DSA MeisterGeister\
Laufwerk: E:\ (Name), NTFS (Format), Fixed (Typ)
Prozessoranzahl: 16
WorkingSet: 324943872
Renderingebene: 2 (Hardwarebeschleunigung; DirectX >= 9.0)
Auflösung: 5120x1440 (5120x1377)
Bildschirme: 1
\\.\DISPLAY1 ({X=0,Y=0,Width=5120,Height=1440}, BitsPerPixel: 32, Primary: True)
Nr=0, Name=\\.\DISPLAY1\Monitor0, DeviceString=Generic PnP Monitor, StateFlags=AttachedToDesktop, MultiDriver
Nr=1, Name=, DeviceString=, StateFlags=0
Nr=2, Name=, DeviceString=, StateFlags=0
Nr=3, Name=, DeviceString=, StateFlags=0
Nr=4, Name=, DeviceString=, StateFlags=0
Nr=5, Name=, DeviceString=, StateFlags=0
Nr=6, Name=, DeviceString=, StateFlags=0
Nr=7, Name=, DeviceString=, StateFlags=0

Performance:
00:00:00.4022393: Programmstart
00:00:15.1527932: Daten aus Datenbank laden

**Comment by Koizumi85** [comment]
Hallo zusammen. Gibt es schon Pläne wann eine neue Version mit diesem Fix released wird? Ohne diesen Fix ist Release 2.6 für mich leider nicht wirklich nutzbar weswegen Ich noch auf 2.5 bleiben muss.

**Comment by Constructor0987** [comment]
Hallo.
Das Problem bin ich angegangen und hatte ich letztens auch testen können, sodass ich eine neue Version innerhalb der nächsten Woche wohl veröffentlichen kann. Bis dahin solltest du aber auch **mit nicht geöffnetem Kampf-Tool** deine Helden einfügen können. Sobald du hier fertig bist, kannst du das Kampf-Tool wieder öffnen.
